#!/bin/bash

function show_help() {
    echo "Usage:"
    echo "    ./create <name> [method]"
    if [ $# -gt 0 -a "$1" -gt 0 ]; then
        exit $1
    fi
}

function create_file() {
    mkdir "$1"
    src="$1/$1_test.go"
    touch $src
    cat > "$src" <<-_END
		package main
		
		import (
			"testing"
		
			"github.com/stretchr/testify/assert"
		)
		
		func Test_FUNC(t *testing.T) {
			assert.True(t, FUNC())
		}
		
		func Benchmark_FUNC(b *testing.B) {
			// Initializations here.
			b.ResetTimer()
			for i := 0; i < b.N; i++ {
				FUNC()
			}
		}
		
		func FUNC() bool {
			return true
		}
	_END
    if [ "$2" ]; then
        sed -i 's/FUNC/'$2'/g' "$src"
    fi
}

function run() {
    if [ $# -ne 1 ]; then
        show_help 1
    fi
    dir_name=`echo $1 | sed -n 's/\([A-Z][A-Z]*\)/_\L\1/gp'`;
    if [ -e "$dir_name" ]; then
        echo "File $$dir_name already exist"
        show_help 1
    fi
    create_file "$dir_name" "$1"
}

run "${@}"
