#!/bin/bash

function show_help() {
    echo "Usage:"
    echo "    ./create2 <name>"
    if [ $# -gt 0 -a "$1" -gt 0 ]; then
        exit $1
    fi
}

function create_file() {
    mkdir "$1"
    touch "$1/test.in"
    src="$1/$1_test.go"
    touch $src
    cat > "$src" <<-_END
		package main
		
		import (
		    "fmt"
		    "os"
		    "testing"
		
		    "github.com/zhaoyuankui/goutil/alg"
		)
		
		func main() {
		    var a, b int
		    fmt.Scanf("%d %d", &a, &b)
		    fmt.Println(a + b)
		}
		
		func Test_main(t *testing.T) {
		    stdin, stdout := os.Stdin, os.Stdout
		    os.Stdin, _ = os.Open("./test.in")
		    os.Stdout, _ = os.Create("./test.out")
		
		    main()
		
		    // Check
		    alg.AssertEqual(t, "./test.out", []string{"3"})
		
		    os.Stdin, os.Stdout = stdin, stdout
		}
		
		func Benchmark_main(b *testing.B) {
		    // Initializations here.
		    stdin, stdout := os.Stdin, os.Stdout
		    os.Stdin, _ = os.Open("./test.in")
		    os.Stdout, _ = os.Open("/dev/null")
		    b.ResetTimer()
		
		    for i := 0; i < b.N; i++ {
		        os.Stdin.Seek(0, 0)
		        main()
		    }
		
		    os.Stdin, os.Stdout = stdin, stdout
		}
	_END
}

function run() {
    if [ $# -ne 1 ]; then
        show_help 1
    fi
    dir_name=$1
    if [ -e "$dir_name" ]; then
        echo "File $dir_name already exist"
        show_help 1
    fi
    create_file "$dir_name"
}

run "${@}"
